"""add isbn13 to literatures

Revision ID: 071d80be1e29
Revises: 1a58086a0a47
Create Date: 2026-08-22 12:20:38.723210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071d80be1e29'
down_revision: Union[str, Sequence[str], None] = '1a58086a0a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literatures', sa.Column('isbn13', sa.String(length=13), nullable=True))
    op.alter_column('literatures', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('literatures', 'author',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_literatures_isbn13'), 'literatures', ['isbn13'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_literatures_isbn13'), table_name='literatures')
    op.alter_column('literatures', 'author',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('literatures', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('literatures', 'isbn13')
    # ### end Alembic commands ###
