"""change tags unique constraint

Revision ID: 1a58086a0a47
Revises: 82725512f248
Create Date: 2026-08-17 00:29:00.484485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a58086a0a47'
down_revision: Union[str, Sequence[str], None] = '82725512f248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_bibliography_cache',
    sa.Column('nid', sa.String(length=20), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('author_kor', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('translator', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('published_year', sa.String(length=10), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.create_unique_constraint('uq_tags_category_name', 'tags', ['category', 'name'])
    op.alter_column('translations', 'language',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('translations', 'translator',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('translations', 'publisher',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'publisher',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('translations', 'translator',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('translations', 'language',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint('uq_tags_category_name', 'tags', type_='unique')
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('lti_bibliography_cache')
    # ### end Alembic commands ###
