"""feat: update translation metadata

Revision ID: 90f39bad0c63
Revises: a6afa6937cfe
Create Date: 2026-09-21 22:27:33.604011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f39bad0c63'
down_revision: Union[str, Sequence[str], None] = 'a6afa6937cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lti_bibliography_cache', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('lti_bibliography_cache', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('lti_bibliography_cache', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('translations', sa.Column('lti_nid', sa.String(length=50), nullable=True))
    op.add_column('translations', sa.Column('author', sa.Text(), nullable=True))
    op.add_column('translations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('translations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('translations', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('translations', sa.Column('preview_url', sa.Text(), nullable=True))
    op.alter_column('translations', 'translated_title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('translations', 'language',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('translations', 'translator',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('translations', 'publisher',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('translations', 'isbn',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_translations_google_books_id'), table_name='translations')
    op.create_index(op.f('ix_translations_google_books_id'), 'translations', ['google_books_id'], unique=False)
    op.create_index(op.f('ix_translations_lti_nid'), 'translations', ['lti_nid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_lti_nid'), table_name='translations')
    op.drop_index(op.f('ix_translations_google_books_id'), table_name='translations')
    op.create_index(op.f('ix_translations_google_books_id'), 'translations', ['google_books_id'], unique=True)
    op.alter_column('translations', 'isbn',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('translations', 'publisher',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('translations', 'translator',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('translations', 'language',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('translations', 'translated_title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('translations', 'preview_url')
    op.drop_column('translations', 'source_url')
    op.drop_column('translations', 'description')
    op.drop_column('translations', 'country')
    op.drop_column('translations', 'author')
    op.drop_column('translations', 'lti_nid')
    op.drop_column('lti_bibliography_cache', 'description')
    op.drop_column('lti_bibliography_cache', 'country')
    op.drop_column('lti_bibliography_cache', 'title')
    # ### end Alembic commands ###
