"""update literature schema

Revision ID: f9c7373ef182
Revises: 071d80be1e29
Create Date: 2026-08-27 15:30:02.336926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c7373ef182'
down_revision: Union[str, Sequence[str], None] = '071d80be1e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('literatures', 'literature_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('literatures', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literatures', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('literatures', 'literature_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
