"""feat: update translations table

Revision ID: fe876218dafa
Revises: f9c7373ef182
Create Date: 2026-09-21 11:43:01.889365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe876218dafa'
down_revision: Union[str, Sequence[str], None] = 'f9c7373ef182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorites', 'literatures', ['work_id'], ['work_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'literature_tags', 'literatures', ['work_id'], ['work_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('literatures_isbn13_key'), 'literatures', type_='unique')
    op.drop_index(op.f('ix_literatures_isbn13'), table_name='literatures')
    op.create_index(op.f('ix_literatures_isbn13'), 'literatures', ['isbn13'], unique=True)
    op.create_foreign_key(None, 'recommendations', 'literatures', ['work_id'], ['work_id'], ondelete='CASCADE')
    op.add_column('translations', sa.Column('google_books_id', sa.String(length=100), nullable=True))
    op.alter_column('translations', 'language',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_translations_google_books_id'), 'translations', ['google_books_id'], unique=True)
    op.create_foreign_key(None, 'translations', 'literatures', ['work_id'], ['work_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'visual_aids', 'literatures', ['work_id'], ['work_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visual_aids', type_='foreignkey')
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_index(op.f('ix_translations_google_books_id'), table_name='translations')
    op.alter_column('translations', 'language',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('translations', 'google_books_id')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_literatures_isbn13'), table_name='literatures')
    op.create_index(op.f('ix_literatures_isbn13'), 'literatures', ['isbn13'], unique=False)
    op.create_unique_constraint(op.f('literatures_isbn13_key'), 'literatures', ['isbn13'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'literature_tags', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    # ### end Alembic commands ###
